### ISSUE TITLE
jQA tries to load rules from jQA report file

### ISSUE THREAD

**Issue by jensnerche** [jQAssistant/jqa-core-framework#43]
If all jQA artifacts are stored in one directory (e.g. jqassistant), the RuleSetReader tries to read rules from the report file but failes:

Reading rules from directory C:\Users\jn\projects\jqassistant-plugins\jqassistant
Adding rules from file C:\Users\jn\projects\jqassistant-plugins\jqassistant\jqassistant-rules\default.xml
Adding rules from file C:\Users\jn\projects\jqassistant-plugins\jqassistant\report\jqassistant-report.xml
[main] INFO com.buschmais.jqassistant.core.analysis.impl.RuleSetReaderImpl - Reading rules from 'default.xml'.
[main] INFO com.buschmais.jqassistant.core.analysis.impl.RuleSetReaderImpl - Reading rules from 'jqassistant-report.xml'.
Exception in thread "main" java.lang.IllegalArgumentException: Cannot read rules from 'jqassistant-report.xml'.
        at com.buschmais.jqassistant.core.analysis.impl.RuleSetReaderImpl.read(RuleSetReaderImpl.java:64)
        at com.buschmais.jqassistant.scm.cli.AnalyzeTask.readRules(AnalyzeTask.java:143)
        at com.buschmais.jqassistant.scm.cli.AnalyzeTask.resolveEffectiveRules(AnalyzeTask.java:109)
        at com.buschmais.jqassistant.scm.cli.AnalyzeTask.executeTask(AnalyzeTask.java:60)
        at com.buschmais.jqassistant.scm.cli.AbstractJQATask.run(AbstractJQATask.java:80)
        at com.buschmais.jqassistant.scm.cli.Main.executeTask(Main.java:255)
        at com.buschmais.jqassistant.scm.cli.Main.interpretCommandLine(Main.java:228)
        at com.buschmais.jqassistant.scm.cli.Main.main(Main.java:145)
Caused by: javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 112; cvc-elt.1: Deklaration des Elements "jqa-report:jqassistant-report" kann nicht gefunden werden.]
      at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:578)
      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:264)
      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:236)
      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:291)
      at com.buschmais.jqassistant.core.analysis.impl.RuleSetReaderImpl.read(RuleSetReaderImpl.java:62)
      ... 7 more
  Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 112; cvc-elt.1: Deklaration des Elements "jqa-report:jqassistant-report" kann nicht gefunden werden.
      at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
      at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
      at com.sun.org.apache.xnternal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
      at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
      at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
      at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1906)
      at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
      at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
      at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:101)
      at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:150)
      at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
      at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:378)
      at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:604)
      at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3122)
      at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
      at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
      at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
      at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
      at com.sun.org.apache.xercesal.parsers.XMLParser.parse(XMLParser.java:141)
      at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
      at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
      ... 10 more
  :jqaanalyze FAILED

**Comment by obfischer** [comment]
Hi Jens,
does the problem still exits? Otherwise we would like to close this issue for now.
