### ISSUE TITLE
Trying to scan remote Jira server with plugin but it wants a cert even if only basic auth required

### ISSUE THREAD

**Issue by Artimunor** [jQAssistant/jqa-core-framework#52]
OS:
- Windows Server 2016

Versions:
- jqassistant-commandline-neo4jv3-1.7.0
- jqa-jira-plugin v0.0.2

I am trying to analyse a Jira server with the scan command using the jqa-jira-plugin and i get the error it wants a cert.
This strikes me as odd since we are doing other rest calls to it with just basic auth over https.
However there is some [documentation ](https://github.com/softvis-research/jqa-jira-plugin/blob/2e31e213d5be29a0aba104f7e9fbb890f9d73433/README.md#custom-certificate) about certs on their github so i imported the cert my browser has after login to cacerts, however i am still getting the following error, any idea what might cause this?

> 2020-07-10 08:45:57.676 [main] INFO JiraScannerPlugin - Jira plugin looks for files named 'jira-plugin-configuration.xml'.
> Exception in thread "main" com.buschmais.jqassistant.core.scanner.impl.UnrecoverableScannerException: Unexpected problem encountered while scanning: item='D:\jqassistant-commandline-neo4jv3-1.8.0\bin\jira-plugin-configuration.xml', path='D:/jqassistant-commandline-neo4jv3-1.8.0/bin/jira-plugin-configuration.xml', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@2ecc4be7, org.jqassistant.contrib.plugin.jira.scanner.JiraScannerPlugin@e296794]'. Please report this error including the full stacktrace (continueOnError=false).
>         at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:100)
>         at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
>         at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:35)
>         at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:21)
>         at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:120)
>         at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:80)
>         at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
>         at com.buschmais.jqassistant.commandline.task.ScanTask.scan(ScanTask.java:96)
>         at com.buschmais.jqassistant.commandline.task.ScanTask.executeTask(ScanTask.java:77)
>         at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.run(AbstractStoreTask.java:47)
>         at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:254)
>         at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:203)
>         at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:195)
>         at com.buschmais.jqassistant.commandline.Main.run(Main.java:78)
>         at com.buschmais.jqassistant.commandline.Main.main(Main.java:49)
> Caused by: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.lambda$doExecute$4(ApacheAsyncHttpClient.java:345)
>         at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:424)
>         at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
>         at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
>         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
>         at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doFailed$1(SettableFuturePromiseHttpPromiseAsyncClient.java:42)
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:327)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:270)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:265)
>         at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:646)
>         at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:465)
>         at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:361)
>         at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
>         at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:451)
>         at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1078)
>         at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1065)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1012)
>         at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:284)
>         at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:352)
>         at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:508)
>         at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
>         at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
>         at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
>         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
>         ... 1 more
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
>         at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
>         at java.base/sun.security.validator.Validator.validate(Validator.java:264)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
>         at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:624)
>         ... 19 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
>         at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
>         at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
>         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
>         ... 25 more

**Comment by Artimunor** [comment]
I was able to work around this issue by using:
`keytool -import -alias JIRA -file jira.crt -cacerts`
instead of 
`keytool -import -alias JIRA -file jira.crt -keystore cacerts`

please note here i am using Java11
